name: Test

on:
  push:
    branches: [main]
  pull_request:
  workflow_call:

jobs:
  luacheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: lunarmodules/luacheck@v1

  unittest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - run: pip install lupa
      - run: python -m unittest discover -s tests -v
